FROM golang:{{ .GoVersion }}-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o main ./cmd/api/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/main .
{{- if .UseDB }}
# Add migration files copy here if needed
{{- end }}
CMD ["./main"]